import React, { createContext, useContext, useState, useEffect } from 'react';

// -----------------------------------------------------------------------
// Translation strings for all 4 languages
// -----------------------------------------------------------------------
const translations = {
  en: {
    // Auth
    appTagline: 'Professional Aquatic Security',
    emailPlaceholder: 'Email Address',
    passwordPlaceholder: 'Password',
    macPlaceholder: 'Hardware MAC Address',
    forgotPassword: 'Forgot password?',
    btnLogin: 'Access System',
    btnSignup: 'Initialize Kit',
    btnReset: 'Send Instructions',
    processing: 'Processing...',
    newOperator: 'New operator?',
    integrateKit: 'Integrate Kit',
    returningOperator: 'Returning operator?',
    signIn: 'Sign In',
    resetSent: 'Password reset email sent!',
    checkEmail: 'Check your email for the confirmation link!',
    // Language Picker
    langLabel: 'Language',
    // Dashboard Header
    dashTitle: 'AquaGuard Hub',
    secureRelay: 'Secure Relay Active',
    liveTab: 'Live Analytics',
    aquabookTab: 'AquaBook',
    logOut: 'Log Out',
    // AquaBook
    aquabookTitle: 'AquaBook Directory',
    aquabookSubtitle: 'Select a phylum division to explore detailed bio-histories, origin data, feeding strategies, and real imagery.',
    fishesLabel: 'Fishes',
    prawnLabel: 'Prawns',
    crabsLabel: 'Crabs',
    varietiesLogged: '5 Varieties Logged',
    returnToDirectory: '← Return to Directory',
    knownVariants: 'Known',
    variants: 'Variants',
    backTo: '← Back to',
    bioHistory: '🐟 Bio History',
    geoOrigin: '🌍 Geographic Origin',
    feedingDetails: '🍽️ Feeding Details',
    commercialProfit: '💰 Commercial Profitability',
    inspectProfile: 'Inspect Profile',
    askAquabot: '🤖 Ask AquaBot About This Species',
    // Sensor Modal
    biologicalImportance: 'Biological Importance',
    optimalTarget: 'Optimal Target',
    deviationRisk: 'Deviation Risk',
    closePanel: 'Close Analytics Panel',
    // Controls
    dosePh: 'Dose pH Buffer',
    circulate: 'Circulate',
    chiller: 'Chiller',
    automatedTitle: 'Automated Lifeline Overrides',
    automatedSub: 'Manual intervention controls bypassing edge routing',
    viewDetails: 'View Details ↗',
    // Chatbot
    chatTitle: 'AquaBot',
    chatSubtitle: 'Voice & Text Assistant',
    chatPlaceholder: 'Ask me anything about your aquaculture...',
    chatSend: 'Send',
    chatListen: 'Listening...',
    chatClose: 'Close',
    chatGreeting: 'Hello! I am AquaBot, your AquaGuard assistant. You can ask me about sensor readings, fish species, water quality, or any aquaculture topic. Try tapping the mic!',
    chatNoSupport: 'Voice recognition is not supported in this browser. Please use Chrome.',
    chatThinking: 'Thinking...',
  },
  te: {
    appTagline: 'వృత్తిపరమైన జలచర భద్రత',
    emailPlaceholder: 'ఇమెయిల్ చిరునామా',
    passwordPlaceholder: 'పాస్‌వర్డ్',
    macPlaceholder: 'హార్డ్‌వేర్ MAC చిరునామా',
    forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?',
    btnLogin: 'సిస్టమ్ యాక్సెస్',
    btnSignup: 'కిట్ ప్రారంభించండి',
    btnReset: 'సూచనలు పంపండి',
    processing: 'ప్రాసెస్ అవుతోంది...',
    newOperator: 'కొత్త ఆపరేటర్?',
    integrateKit: 'కిట్ ఇంటిగ్రేట్ చేయండి',
    returningOperator: 'తిరిగి వచ్చే ఆపరేటర్?',
    signIn: 'సైన్ ఇన్',
    resetSent: 'పాస్‌వర్డ్ రీసెట్ ఇమెయిల్ పంపబడింది!',
    checkEmail: 'ధృవీకరణ లింక్ కోసం మీ ఇమెయిల్ చూడండి!',
    langLabel: 'భాష',
    dashTitle: 'AquaGuard హబ్',
    secureRelay: 'సురక్షిత రిలే యాక్టివ్',
    liveTab: 'లైవ్ అనలిటిక్స్',
    aquabookTab: 'అక్వాబుక్',
    logOut: 'లాగ్ అవుట్',
    aquabookTitle: 'అక్వాబుక్ డైరెక్టరీ',
    aquabookSubtitle: 'జాతుల వివరాలు, మూలం, ఆహారం వ్యూహాలను అన్వేషించడానికి ఒక డివిజన్ ఎంచుకోండి.',
    fishesLabel: 'చేపలు',
    prawnLabel: 'రొయ్యలు',
    crabsLabel: 'పీతలు',
    varietiesLogged: '5 రకాలు నమోదైనవి',
    returnToDirectory: '← డైరెక్టరీకి తిరిగి',
    knownVariants: 'తెలిసిన',
    variants: 'రకాలు',
    backTo: '← తిరిగి',
    bioHistory: '🐟 జీవ చరిత్ర',
    geoOrigin: '🌍 భౌగోళిక మూలం',
    feedingDetails: '🍽️ ఆహారం వివరాలు',
    commercialProfit: '💰 వాణిజ్య లాభదాయకత',
    inspectProfile: 'ప్రొఫైల్ పరిశీలించండి',
    askAquabot: '🤖 ఈ జాతి గురించి AquaBot అడగండి',
    biologicalImportance: 'జీవ ప్రాముఖ్యత',
    optimalTarget: 'సరైన లక్ష్యం',
    deviationRisk: 'విచలన ప్రమాదం',
    closePanel: 'ప్యానెల్ మూయండి',
    dosePh: 'pH బఫర్ ఇవ్వండి',
    circulate: 'సర్క్యులేట్ చేయండి',
    chiller: 'చిల్లర్',
    automatedTitle: 'స్వయంచాలక నియంత్రణలు',
    automatedSub: 'మాన్యువల్ జోక్యం నియంత్రణలు',
    viewDetails: 'వివరాలు చూడండి ↗',
    chatTitle: 'అక్వాబాట్',
    chatSubtitle: 'వాయిస్ & టెక్స్ట్ సహాయకుడు',
    chatPlaceholder: 'జలచర వ్యవసాయం గురించి నన్ను అడగండి...',
    chatSend: 'పంపండి',
    chatListen: 'వింటోంది...',
    chatClose: 'మూయండి',
    chatGreeting: 'నమస్కారం! నేను అక్వాబాట్, మీ AquaGuard సహాయకుడు. సెన్సర్ రీడింగ్‌లు, చేపల జాతులు, నీటి నాణ్యత గురించి అడగవచ్చు. మైక్ నొక్కండి!',
    chatNoSupport: 'ఈ బ్రౌజర్‌లో వాయిస్ రికగ్నిషన్ మద్దతు లేదు. Chrome వాడండి.',
    chatThinking: 'ఆలోచిస్తోంది...',
  },
  ta: {
    appTagline: 'தொழில்முறை நீர்வாழ் பாதுகாப்பு',
    emailPlaceholder: 'மின்னஞ்சல் முகவரி',
    passwordPlaceholder: 'கடவுச்சொல்',
    macPlaceholder: 'வன்பொருள் MAC முகவரி',
    forgotPassword: 'கடவுச்சொல் மறந்தீர்களா?',
    btnLogin: 'அமைப்பை அணுகவும்',
    btnSignup: 'கிட்டை துவக்கவும்',
    btnReset: 'வழிமுறைகள் அனுப்பவும்',
    processing: 'செயலாக்குகிறது...',
    newOperator: 'புதிய இயக்குநரா?',
    integrateKit: 'கிட்டை ஒருங்கிணைக்கவும்',
    returningOperator: 'திரும்பி வரும் இயக்குநரா?',
    signIn: 'உள்நுழைக',
    resetSent: 'கடவுச்சொல் மீட்டமைப்பு மின்னஞ்சல் அனுப்பப்பட்டது!',
    checkEmail: 'உறுதிப்படுத்தல் இணைப்புக்காக மின்னஞ்சலை சரிபார்க்கவும்!',
    langLabel: 'மொழி',
    dashTitle: 'AquaGuard மையம்',
    secureRelay: 'பாதுகாப்பான ரிலே செயலில் உள்ளது',
    liveTab: 'நேரடி பகுப்பாய்வு',
    aquabookTab: 'அக்வாபுக்',
    logOut: 'வெளியேறு',
    aquabookTitle: 'அக்வாபுக் அடைவு',
    aquabookSubtitle: 'இனங்களின் விவரங்கள், தோற்றம், உணவு உத்திகளை ஆராய ஒரு பிரிவை தேர்ந்தெடுக்கவும்.',
    fishesLabel: 'மீன்கள்',
    prawnLabel: 'இறால்கள்',
    crabsLabel: 'நண்டுகள்',
    varietiesLogged: '5 வகைகள் பதிவாகின',
    returnToDirectory: '← அடைவுக்கு திரும்பு',
    knownVariants: 'அறிந்த',
    variants: 'வகைகள்',
    backTo: '← திரும்பு',
    bioHistory: '🐟 உயிரியல் வரலாறு',
    geoOrigin: '🌍 புவியியல் தோற்றம்',
    feedingDetails: '🍽️ உணவு விவரங்கள்',
    commercialProfit: '💰 வணிக லாபம்',
    inspectProfile: 'சுயவிவரத்தை ஆய்வு செய்க',
    askAquabot: '🤖 இந்த இனம் பற்றி AquaBot கேளுங்கள்',
    biologicalImportance: 'உயிரியல் முக்கியத்துவம்',
    optimalTarget: 'சரியான இலக்கு',
    deviationRisk: 'விலகல் அபாயம்',
    closePanel: 'பலகத்தை மூடவும்',
    dosePh: 'pH இடையகம் கொடு',
    circulate: 'சுழற்றவும்',
    chiller: 'குளிரூட்டி',
    automatedTitle: 'தானியங்கி கட்டுப்பாடுகள்',
    automatedSub: 'கையேடு தலையீட்டு கட்டுப்பாடுகள்',
    viewDetails: 'விவரங்களைக் காண்க ↗',
    chatTitle: 'அக்வாபாட்',
    chatSubtitle: 'குரல் மற்றும் உரை உதவியாளர்',
    chatPlaceholder: 'நீர்வாழ் வளர்ப்பு பற்றி கேளுங்கள்...',
    chatSend: 'அனுப்பு',
    chatListen: 'கேட்கிறது...',
    chatClose: 'மூடு',
    chatGreeting: 'வணக்கம்! நான் அக்வாபாட், உங்கள் AquaGuard உதவியாளர். சென்சார் அளவீடுகள், மீன் இனங்கள், நீர் தரம் பற்றி கேளுங்கள். மைக்கை அழுத்துங்கள்!',
    chatNoSupport: 'இந்த உலாவியில் குரல் அங்கீகாரம் ஆதரிக்கப்படவில்லை. Chrome பயன்படுத்தவும்.',
    chatThinking: 'யோசிக்கிறது...',
  },
  hi: {
    appTagline: 'पेशेवर जलीय सुरक्षा',
    emailPlaceholder: 'ईमेल पता',
    passwordPlaceholder: 'पासवर्ड',
    macPlaceholder: 'हार्डवेयर MAC पता',
    forgotPassword: 'पासवर्ड भूल गए?',
    btnLogin: 'सिस्टम एक्सेस करें',
    btnSignup: 'किट आरंभ करें',
    btnReset: 'निर्देश भेजें',
    processing: 'प्रक्रिया हो रही है...',
    newOperator: 'नए ऑपरेटर?',
    integrateKit: 'किट एकीकृत करें',
    returningOperator: 'वापस आए ऑपरेटर?',
    signIn: 'साइन इन',
    resetSent: 'पासवर्ड रीसेट ईमेल भेजा गया!',
    checkEmail: 'पुष्टिकरण लिंक के लिए अपना ईमेल जांचें!',
    langLabel: 'भाषा',
    dashTitle: 'AquaGuard हब',
    secureRelay: 'सुरक्षित रिले सक्रिय',
    liveTab: 'लाइव एनालिटिक्स',
    aquabookTab: 'एक्वाबुक',
    logOut: 'लॉग आउट',
    aquabookTitle: 'एक्वाबुक निर्देशिका',
    aquabookSubtitle: 'प्रजातियों के विवरण, उत्पत्ति और खाद्य रणनीतियों का पता लगाने के लिए एक विभाग चुनें।',
    fishesLabel: 'मछलियाँ',
    prawnLabel: 'झींगे',
    crabsLabel: 'केकड़े',
    varietiesLogged: '5 किस्में दर्ज हैं',
    returnToDirectory: '← निर्देशिका पर वापस',
    knownVariants: 'ज्ञात',
    variants: 'किस्में',
    backTo: '← वापस',
    bioHistory: '🐟 जैव इतिहास',
    geoOrigin: '🌍 भौगोलिक उत्पत्ति',
    feedingDetails: '🍽️ आहार विवरण',
    commercialProfit: '💰 व्यावसायिक लाभप्रदता',
    inspectProfile: 'प्रोफ़ाइल देखें',
    askAquabot: '🤖 इस प्रजाति के बारे में AquaBot से पूछें',
    biologicalImportance: 'जैविक महत्व',
    optimalTarget: 'इष्टतम लक्ष्य',
    deviationRisk: 'विचलन जोखिम',
    closePanel: 'पैनल बंद करें',
    dosePh: 'pH बफर दें',
    circulate: 'परिसंचरण करें',
    chiller: 'चिलर',
    automatedTitle: 'स्वचालित नियंत्रण',
    automatedSub: 'मैन्युअल हस्तक्षेप नियंत्रण',
    viewDetails: 'विवरण देखें ↗',
    chatTitle: 'एक्वाबॉट',
    chatSubtitle: 'वॉयस और टेक्स्ट सहायक',
    chatPlaceholder: 'जलकृषि के बारे में कोई भी प्रश्न पूछें...',
    chatSend: 'भेजें',
    chatListen: 'सुन रहा है...',
    chatClose: 'बंद करें',
    chatGreeting: 'नमस्ते! मैं एक्वाबॉट हूँ, आपका AquaGuard सहायक। सेंसर रीडिंग, मछली की प्रजातियाँ, जल गुणवत्ता के बारे में पूछें। माइक दबाएँ!',
    chatNoSupport: 'इस ब्राउज़र में वॉयस पहचान समर्थित नहीं है। Chrome का उपयोग करें।',
    chatThinking: 'सोच रहा है...',
  }
};

// Language code → SpeechRecognition / SpeechSynthesis BCP-47 locale
export const langLocales = {
  en: 'en',
  te: 'te',
  ta: 'ta',
  hi: 'hi',
};

export const languageOptions = [
  { code: 'en', label: 'English',  flag: '🇬🇧' },
  { code: 'te', label: 'తెలుగు',   flag: '🇮🇳' },
  { code: 'ta', label: 'தமிழ்',    flag: '🇮🇳' },
  { code: 'hi', label: 'हिन्दी',   flag: '🇮🇳' },
];

// -----------------------------------------------------------------------
// Context
// -----------------------------------------------------------------------
const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('aq_lang') || 'en');

  useEffect(() => {
    localStorage.setItem('aq_lang', lang);
  }, [lang]);

  const t = (key) => translations[lang]?.[key] ?? translations['en'][key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLang = () => useContext(LanguageContext);
export default LanguageContext;
